# Generated by Django 4.2.7 on 2023-12-04 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mypage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
