# Generated by Django 4.2.7 on 2023-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_customuser_email_alter_customuser_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token_created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
