# Generated by Django 4.2.7 on 2023-11-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0002_alter_post_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompleteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FindItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Post",
            new_name="AskItem",
        ),
    ]
