# Generated by Django 4.2.7 on 2023-11-27 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0003_alter_askitem_author_alter_completeitem_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="askitem",
            name="place",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="completeitem",
            name="place",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="finditem",
            name="place",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="askitem",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="askitem",
            name="title",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="completeitem",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="completeitem",
            name="title",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="finditem",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="finditem",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
