# Generated by Django 4.2.7 on 2023-11-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0005_category_askitem_category_completeitem_category_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="askitem",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="message/images/ask/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="completeitem",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="message/images/complete/%Y/%m/%d/"
            ),
        ),
        migrations.AddField(
            model_name="finditem",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="message/images/find/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="askitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.category",
            ),
        ),
        migrations.AlterField(
            model_name="completeitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.category",
            ),
        ),
        migrations.AlterField(
            model_name="finditem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.category",
            ),
        ),
    ]
