# Generated by Django 4.2.7 on 2023-11-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0006_alter_category_options_askitem_head_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="head_image",
            field=models.ImageField(
                blank=True, upload_to="message/images/category/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="askitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.category",
            ),
        ),
        migrations.AlterField(
            model_name="completeitem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.category",
            ),
        ),
        migrations.AlterField(
            model_name="finditem",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="message.category",
            ),
        ),
    ]
