# Generated by Django 4.2.7 on 2023-11-22 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("message", "0007_category_head_image_alter_askitem_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completeitem",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "askPost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.askitem",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "findPost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="message.finditem",
                    ),
                ),
            ],
        ),
    ]
