# Generated by Django 4.2.7 on 2023-11-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("message", "0008_alter_completeitem_created_at_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="askPost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.askitem",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="findPost",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="message.finditem",
            ),
        ),
    ]
