# Generated by Django 4.2.7 on 2023-11-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_alter_completeitem_created_at'),
        ('message', '0010_comment_completepost'),
    ]

    operations = [
    ]
